version: "3.8"

services:
  express-app:
    build: .
    container_name: express-app
    ports:
      - "5000:5000"
    depends_on:
      - nginx

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
